{{- if not .Values.existingSecrets.backend.name }}
{{- $anyBackendSecrets := false }}
{{- range .Values.backend.secrets }}
  {{- if . }}
    {{- $anyBackendSecrets = true }}
  {{- end }}
{{- end }}
{{- if $anyBackendSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secrets
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "base.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $key, $value := .Values.backend.secrets }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
