apiVersion: v2
name: http-mirror
description: A Helm chart for HTTP Mirror - mirrors HTTP directory listings and serves them via web server
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/jhofer-cloud/http-mirror
maintainers:
  - name: ojsef39
    email: me+github@jhofer.de
dependencies:
  - name: base
    repository: https://charts.jhofer.org
    tags:
      - base
    version: 1.x.x
