apiVersion: v2
name: proxmox-exporter
description: A Helm chart for Prometheus Proxmox VE Exporter
type: application
version: 1.1.2
appVersion: "3.5.3"
dependencies:
  - name: base
    repository: https://charts.jhofer.org
    tags:
      - base
    version: 1.x.x
maintainers:
  - name: ojsef39
    email: me@jhofer.de
    url: https://github.com/ojsef39
